services:
  quizbowl_backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    # image: react-flask-app-api
    depends_on:
      - quizbowl_postgres
    ports:
      - "5001:5000"
    # expose:
    #   - "5001"
    # links:
    #   - quizbowl_postgres:quizbowl_postgres
    networks:
      - quizbowl_net
  quizbowl_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - quizbowl_backend
    ports:
      - "3001:80"
    # links:
    #   - quizbowl_backend:quizbowl_backend
    networks:
      - quizbowl_net
  quizbowl_postgres:
    container_name: quizbowl_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    # expose:
    #   - "5430"
    networks:
      - quizbowl_net
networks:
  quizbowl_net:
    driver: bridge